# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "sam"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
parameter_overrides = "DataSourceCodeBucket=\"data-source-code-deploy-us-east-1\" DataSourceCodeKey=\"a/v1/DXT4ZLETDA6WXUHVEUWQ6CR57TCI6OVCDOLGBIXOQVX4H5YBZ5ZA/s3.zip\" DataSourceName=\"s3-csv-cloudwatch-reader\""
stack_name = "metric-timeshift"
s3_prefix = "metric-timeshift"
region = "us-east-1"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[metric-timeshift.deploy.parameters]
stack_name = "metric-timeshift"
resolve_s3 = true
s3_prefix = "metric-timeshift"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "DataSourceCodeBucket=\"metric-archive-data-source-us-east-1-prod\" DataSourceCodeKey=\"metric-timeshift-s3.zip\" DataSourceName=\"s3-csv-cloudwatch-reader\""
image_repositories = []
